version: '3.5'
services:
  cli:
    build:
      context: ./../.
      dockerfile: ./.docker/cli/Dockerfile
    volumes:
      - ./../:/app
    networks:
      - network-coffee-shop
    working_dir: /app
    env_file:
      - .env

  db:
    image: postgres:15.2
    container_name: ${POSTGRES_HOST}
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./db-postgres:/docker-entrypoint-initdb.d/
    networks:
      - network-coffee-shop
    ports:
      - 8001:5432
    depends_on:
      - cli

  api-rest:
    container_name: api-rest  # @todo: put into a variable name.
    build:
      context: ./../.
      dockerfile: ./.docker/api-rest/Dockerfile
    volumes:
      - ./../:/app
    ports:
      - 8004:8000
    networks:
      - network-coffee-shop
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - cli
      - db

  http:
    image: nginx:1.23.3
    volumes:
      - ./http/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8005:80
    networks:
      - network-coffee-shop
    depends_on:
      - cli
      - db
      - api-rest

networks:
  network-coffee-shop:
    driver: bridge
